name: finalyearproject
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  air_quality: ^2.0.0

  # Auth Buttons is a flutter widget library, include buttons for authenticating with the most popular social networks like: Google, Facebook, Apple and too other. ("https://pub.dev/packages/auth_buttons")
  auth_buttons: ^2.0.1

  # This Flutter package provides a Avatar Glow Widget with cool background glowing animation. ("https://pub.dev/packages/avatar_glow")
  avatar_glow: ^2.0.2

  # A flutter package for creating badges. ("https://pub.dev/packages/badges")
  badges: ^2.0.1

  cached_network_image: ^2.0.0

  cloud_firestore: ^3.1.1

  # Cross platform package that unifies the work with Platform and wrapps dart:io Platform and dart:html to determine platform of the host machine an info about it. ("https://pub.dev/packages/cross_platform")
  cross_platform: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Flutter plugin for Firebase Auth, enabling Android and iOS authentication using passwords, phone numbers and identity providers like Google, Facebook and Twitter. ("https://pub.dev/packages/firebase_auth")
  firebase_auth: ^3.3.3

  # A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps. ("https://pub.dev/packages/firebase_core")
  firebase_core: ^1.10.5

  flutter_spinkit: ^5.0.0

  # The Font Awesome Icon pack available as set of Flutter Icons. ("https://pub.dev/packages/font_awesome_flutter")
  font_awesome_flutter: ^9.1.0

  gif_view: ^0.0.1

  geolocator: ^7.6.2

  # The google_fonts package for Flutter allows you to easily use any of the 977 fonts (and their variants) from fonts.google.com in your Flutter app. ("https://pub.dev/packages/google_fonts")
  google_fonts: ^2.1.0

  # A Flutter plugin for Google Sign In. ("https://pub.dev/packages/google_sign_in")
  google_sign_in: ^5.2.1

  # A composable, Future-based library for making HTTP requests. ("https://pub.dev/packages/http")
  http: ^0.13.4

  intl: ^0.17.0

  # This package includes 1332 icons of Ionicons v5.4.0. The naming convention is the same as the CSS names, all dashes replaced with underscores. ("https://pub.dev/packages/ionicons")
  ionicons: ^0.1.2

  location: ^4.2.0

  # This Flutter plugin provides an API for querying information about an application package. ("https://pub.dev/packages/package_info_plus")
  package_info_plus: ^1.3.0

  # Flutter plugin for build alert dialogs adapted to the current platform. ("https://pub.dev/packages/platform_alert_dialog")
  platform_alert_dialog: ^1.0.0+2

  provider: ^4.3.2+1

  pull_to_refresh: ^2.0.0

  # Yet another bottom navigation bar, but with a few key promises. ("https://pub.dev/packages/salomon_bottom_bar")
  salomon_bottom_bar: ^3.1.0

  shared_preferences: ^2.0.5

  # A Flutter plugin for launching a URL. Supports iOS, Android, web, Windows, macOS, and Linux. ("https://pub.dev/packages/url_launcher")
  url_launcher: ^6.0.12

  webview_flutter: ^0.3.19+9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/GIF/
    - assets/ElectricityComplaints/
    - assets/PollutionComplaints/
    - assets/SewageComplaints/
    - assets/WomenSafety/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
